In [1]:
#MEAN

numbers=[1,2,3,4,5,6]
n=len(numbers)
sums=sum(numbers)

mean=sums/n

print("Mean is " + str(mean))

Mean is 3.5


In [2]:
#MEDIAN

num = [1, 2, 3, 4, 5]
n = len(num)
num.sort()
  
if n % 2 == 0:
    median1 = num[n//2]
    median2 = num[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = num[n//2]
print("Median is: " + str(median))

Median is: 3


In [3]:
num = [6, 7, 8, 9, 10]
n = len(num)
num.sort()
  
if n % 2 == 0:
    median1 = num[n//2]
    median2 = num[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = num[n//2]
print("Median is: " + str(median))

Median is: 8


In [5]:
def variance(data):
    # Number of observations
     n = len(data)
    # Mean of the data
     mean = sum(data) / n
    # Square deviations
     deviations = [(x - mean) ** 2 for x in data]
    # Variance
    variance = sum(deviations) / n
     return variance

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [9]:
def variance(data):
    # Number of observations
     n = len(data)
    # Mean of the data
     mean = sum(data) / n
    # Square deviations
     deviations = [(x - mean) ** 2 for x in data]
    # Variance
    variance = sum(deviations) / n
     return variance


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [11]:
def variance(data):
    
     n = len(data)
    
     mean = sum(data) / n
    
     deviations = [(x - mean) ** 2 for x in data]

    variance = sum(deviations) / n
     return variance

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [12]:
variance([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

NameError: name 'variance' is not defined

In [14]:
>>>def variance(data):
    
     n = len(data)
    
     mean = sum(data) / n
    
     deviations = [(x - mean) ** 2 for x in data]

    variance = sum(deviations) / n
     return variance

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [16]:
def variance(data):
    
     n = len(data)
    
     mean = sum(data) / n
    
     deviations = [(x - mean) ** 2 for x in data]

    variance = sum(deviations) / n
     return variance

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [17]:
import math

In [18]:
def variance(data, ddof=0):
     n = len(data)
     mean = sum(data) / n
     return sum((x - mean) ** 2 for x in data) / (n - ddof)

In [20]:
 def stdev(data):
     var = variance(data)
    std_dev = math.sqrt(var)
    return std_dev

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [21]:
stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

NameError: name 'stdev' is not defined

In [22]:
#VARIANCE
def variance(data):
...     # Number of observations
...     n = len(data)
...     # Mean of the data
...     mean = sum(data) / n
...     # Square deviations
...     deviations = [(x - mean) ** 2 for x in data]
...     # Variance
...     variance = sum(deviations) / n
...     return variance

In [23]:
variance([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

5.76

In [24]:
import math

In [25]:
#STANDARD DEVIATION
def variance(data, ddof=0):
...     n = len(data)
...     mean = sum(data) / n
...     return sum((x - mean) ** 2 for x in data) / (n - ddof)

In [26]:
def stdev(data):
...     var = variance(data)
...     std_dev = math.sqrt(var)
...     return std_dev

In [27]:
stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

2.4

In [29]:
#VARIANCE AND STANDARD DEVIATION
test_list = [4, 5, 8, 9, 10]
mean = sum(test_list) / len(test_list)
variance = sum([((x - mean) ** 2) for x in test_list]) / len(test_list)
print("vaiance is : " +str(variance))
res = variance ** 0.5
print("Standard deviation of sample is : " + str(res))

vaiance is : 5.36
Standard deviation of sample is : 2.3151673805580453


In [30]:
# copy the data
df_max_scaled = df.copy()

# apply normalization techniques
for column in df_max_scaled.columns:
	df_max_scaled[column] = df_max_scaled[column] / df_max_scaled[column].abs().max()
	
# view normalized data
display(df_max_scaled)


NameError: name 'df' is not defined

In [31]:
# copy the data
df_min_max_scaled = df.copy()

# apply normalization techniques
for column in df_min_max_scaled.columns:
	df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())	

# view normalized data
print(df_min_max_scaled)


NameError: name 'df' is not defined

In [32]:
#NORMALIZATION
from sklearn import preprocessing
import numpy as np
x_array = np.array([2,3,5,6,7,4,8,7,6])
normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)

[[0.11785113 0.1767767  0.29462783 0.35355339 0.41247896 0.23570226
  0.47140452 0.41247896 0.35355339]]


In [33]:

import pandas as pd

df = pd.DataFrame([
				[180000, 110, 18.9, 1400],
				[360000, 905, 23.4, 1800],
				[230000, 230, 14.0, 1300],
				[60000, 450, 13.5, 1500]],
	
				columns=['Col A', 'Col B',
							'Col C', 'Col D'])


display(df)


Col A  Col B  Col C  Col D
0  180000    110   18.9   1400
1  360000    905   23.4   1800
2  230000    230   14.0   1300
3   60000    450   13.5   1500

In [34]:
#NORMALIZATION
n_list=[1,2,3,4,5,6]
list_max=max(n_list)
list_min=min(n_list)
print("value: Normalized value\n")
for x in n_list:
    n=(x-list_min)/(list_max-list_min)
    print("{} : {}".format(x,n))
    

value: Normalized value

1 : 0.0
2 : 0.2
3 : 0.4
4 : 0.6
5 : 0.8
6 : 1.0


In [35]:
n_list=[40,200,30.5,28,54,60]
list_max=max(n_list)
list_min=min(n_list)
print("value: Normalized value\n")
for x in n_list:
    n=(x-list_min)/(list_max-list_min)
    print("{} : {}".format(x,n))
    

value: Normalized value

40 : 0.06976744186046512
200 : 1.0
30.5 : 0.014534883720930232
28 : 0.0
54 : 0.1511627906976744
60 : 0.18604651162790697


In [36]:
#STANDARDIZATION

import math
a=[24,20,67.5,40,5,600]
mean=sum(a)/len(a)
variance=sum((i - mean) ** 2 for i in a) / len(a)
sd=variance**0.5
print("value: Standardized value\n")
for x in a:
    s=(x-mean)/sd
    print("{} : {}".format(x,s))


value: Standardized value

24 : -0.4796512152928269
20 : -0.49844571189205605
67.5 : -0.27526106477621004
40 : -0.40447322889591036
5 : -0.5689250741391653
600 : 2.226756294996169


In [37]:
import math
a=[24,20,67.5,40,5,60]
mean=sum(a)/len(a)
variance=sum((i - mean) ** 2 for i in a) / len(a)
sd=variance**0.5
print("value: Standardized value\n")
for x in a:
    s=(x-mean)/sd
    print("{} : {}".format(x,s))


value: Standardized value

24 : -0.5453864842504663
20 : -0.725928216967862
67.5 : 1.418004859051212
40 : 0.17678044661911654
5 : -1.4029597146580959
60 : 1.079489110206095


In [1]:
#k-means clustering

import math
cluster1 = []
cluster2 = []
cluster3 = []
x1,y1 = 6.2,3.2
x2,y2 = 6.6,3.7
x3,y3 = 6.5,3.0
points =[[5.9,3.2],
         [4.6,2.9],
         [6.2,2.8],
         [4.7,3.2],
         [5.5,4.2],
         [5.0,3.0],
         [4.9,3.1],
         [6.7,3.1],
         [5.1,3.8],
         [6.0,3.0]]

def eucledian_distance(a,b):
    dis1 = math.sqrt((a-x1)**2 + (b-y1)**2)
    dis2 = math.sqrt((a-x2)**2 + (b-y2)**2)
    dis3 = math.sqrt((a-x3)**2 + (b-y3)**2)
    mind = min(dis1,dis2,dis3)
    if(mind == dis1):
        cluster1.append([a,b])
    elif(mind == dis2):
        cluster2.append([a,b])
    else:
        cluster3.append([a,b])
        
for i,j in points:
    eucledian_distance(i,j)
print(cluster1)
print(cluster2)
print(cluster3)
            

[[5.9, 3.2], [4.6, 2.9], [4.7, 3.2], [5.0, 3.0], [4.9, 3.1], [5.1, 3.8], [6.0, 3.0]]
[[5.5, 4.2]]
[[6.2, 2.8], [6.7, 3.1]]


In [2]:
sumi = 0
sumj = 0
for i,j in cluster1:
    sumi = sumi + i
    sumj = sumj + j
nx1 = round(sumi/len(cluster1),2)
ny1 = round(sumj/len(cluster1),2)
print(nx1,ny1)

5.17 3.17


In [6]:
import pandas as pn
import numpy as np

data = pn.read_csv('datasets.csv')
k=3
cent=[[data['x1'][0],data['x2'][0]],[data['x1'][3],data['x2'][3]],[data['x1'][5],data['x2'][5]]]
dt=[]
for i in range(len(data)):
        dt.append([data['x1'][i],data['x2'][i]])
dt=np.array(dt)
dist=[]

print("Centroid 1")
for i in range(len(dt)):
    dist.append(np.linalg.norm(dt[i]-cent[0]))
print(dist)

dist1=[]
print("Centroid 2")
for i in range(len(dt)):
    dist1.append(np.linalg.norm(dt[i]-cent[1]))
print(dist1)

dist2=[]
print("Centroid 3")
for i in range(len(dt)):
    dist2.append(np.linalg.norm(dt[i]-cent[2]))
print(dist2)

cluster1=[]
cluster2=[]
cluster3=[]
for i in range(len(dist)):
    
        if dist[i]==0:
            cluster1.append(dist[i])
        elif dist1[i]==0:
            cluster2.append(dist1[i])
        elif dist2[i]==0:
            cluster3.append(dist2[i])
        else:
            x=min(dist[i],dist1[i],dist2[i])
            if x in dist:
                cluster1.append(x)
            elif x in dist1:
                cluster2.append(x)
            else:
                cluster3.append(x)

print("Clusters")
print(cluster1)
print(cluster2)
print(cluster3)


Centroid 1
[0.0, 1.3341664064126342, 0.5000000000000001, 1.2000000000000002, 1.077032961426901, 0.9219544457292891, 1.004987562112089, 0.8062257748298548, 1.0000000000000002, 0.22360679774997896]
Centroid 2
[1.2000000000000002, 0.3162277660168384, 1.5524174696260025, 0.0, 1.2806248474865696, 0.3605551275463989, 0.22360679774997916, 2.0024984394500787, 0.7211102550927972, 1.3152946437965904]
Centroid 3
[0.9219544457292891, 0.4123105625617664, 1.216552506059644, 0.3605551275463989, 1.3, 0.0, 0.1414213562373093, 1.7029386365926404, 0.8062257748298547, 1.0]
Clusters
[0.0, 0.5000000000000001, 1.077032961426901, 0.8062257748298548, 0.22360679774997896]
[0.3162277660168384, 0.0, 0.7211102550927972]
[0.0, 0.1414213562373093]


In [7]:
import numpy as np
import pandas as pd
from copy import deepcopy


def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)


def main():
    k = 3
    X = pd.read_csv('datasets.csv',index_col=False)
    print(X)

    x1 = X['x1'].values
    x2 = X['x2'].values
    X = np.array(list(zip(x1, x2)))
    print(X)
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape)

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old)
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(X))
    print(clusters)
    error = euclidean(Centroid, Centroid_old, None)
    print(error)
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(X)):
            #print(X[i])
            distances = euclidean(X[i], Centroid)
            #print(distances)
            cluster = np.argmin(distances)
            clusters[i] = cluster

        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error)  
    

if __name__ == "__main__": 
    main()



    x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0
[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]]
Initial Centroids
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.537144692236463
 Centre of the clusters after  1  Iteration 
 [[5.1714287 3.1714287]
 [5.5       4.2      ]
 [6.45      2.95     ]]
Error  ...  1.5886393
 Centre of the clusters after  2  Iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]]
Error  ...  0.5484787
 Centre of the clusters after  3  Iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]]
Error  ...  0.0
